### ISSUE TITLE
build problem on my local

### ISSUE THREAD

**Issue by romani** [checkstyle/metadata-gen#48]
```
$ git pull
Already up-to-date.
✔ ~/java/github/checkstyle/metadata-gen [master|✔] 

$ mvn clean install
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< org.example:metadata-gen >----------------------
[INFO] Building metadata-gen 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ metadata-gen ---
[INFO] Deleting /home/rivanov/java/github/checkstyle/metadata-gen/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ metadata-gen ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 186 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ metadata-gen ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 7 source files to /home/rivanov/java/github/checkstyle/metadata-gen/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ metadata-gen ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 21 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:testCompile (default-testCompile) @ metadata-gen ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/rivanov/java/github/checkstyle/metadata-gen/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ metadata-gen ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.example.JavadocMetadataScraperTest
[ERROR] Tests run: 6, Failures: 5, Errors: 0, Skipped: 0, Time elapsed: 1.458 s <<< FAILURE! - in org.example.JavadocMetadataScraperTest
[ERROR] testFilterModule  Time elapsed: 0.936 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Fully qualified name doesn't match: SuppressionXpathSingleFilter ==> expected: <inputs.suppression-xpath-single-filter.SuppressionXpathSingleFilter> but was: <github.checkstyle.metadata-gen.src.test.resources.java.inputs.suppression-xpath-single-filter.SuppressionXpathSingleFilter>
	at org.example.JavadocMetadataScraperTest.checkModuleMeta(JavadocMetadataScraperTest.java:91)
	at org.example.JavadocMetadataScraperTest.testFilterModule(JavadocMetadataScraperTest.java:31)

[ERROR] testFileFilterModuleAndEmptyViolationMessageKeys  Time elapsed: 0.074 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Fully qualified name doesn't match: BeforeExecutionExclusionFileFilter ==> expected: <inputs.before-execution-exclusion-file-filter.BeforeExecutionExclusionFileFilter> but was: <github.checkstyle.metadata-gen.src.test.resources.java.inputs.before-execution-exclusion-file-filter.BeforeExecutionExclusionFileFilter>
	at org.example.JavadocMetadataScraperTest.checkModuleMeta(JavadocMetadataScraperTest.java:91)
	at org.example.JavadocMetadataScraperTest.testFileFilterModuleAndEmptyViolationMessageKeys(JavadocMetadataScraperTest.java:25)

[ERROR] testCheckModuleAndEnumTokenValues  Time elapsed: 0.085 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Fully qualified name doesn't match: RightCurly ==> expected: <inputs.right-curly-check.RightCurlyCheck> but was: <github.checkstyle.metadata-gen.src.test.resources.java.inputs.right-curly-check.RightCurlyCheck>
	at org.example.JavadocMetadataScraperTest.checkModuleMeta(JavadocMetadataScraperTest.java:91)
	at org.example.JavadocMetadataScraperTest.testCheckModuleAndEnumTokenValues(JavadocMetadataScraperTest.java:20)

[ERROR] testExampleLessModuleDescription  Time elapsed: 0.033 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Fully qualified name doesn't match: ExampleLessUpperEll ==> expected: <inputs.upper-ell-check.ExampleLessUpperEllCheck> but was: <github.checkstyle.metadata-gen.src.test.resources.java.inputs.upper-ell-check.ExampleLessUpperEllCheck>
	at org.example.JavadocMetadataScraperTest.checkModuleMeta(JavadocMetadataScraperTest.java:91)
	at org.example.JavadocMetadataScraperTest.testExampleLessModuleDescription(JavadocMetadataScraperTest.java:42)

[ERROR] testEmptyPropretiesList  Time elapsed: 0.036 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Fully qualified name doesn't match: UpperEll ==> expected: <inputs.upper-ell-check.UpperEllCheck> but was: <github.checkstyle.metadata-gen.src.test.resources.java.inputs.upper-ell-check.UpperEllCheck>
	at org.example.JavadocMetadataScraperTest.checkModuleMeta(JavadocMetadataScraperTest.java:91)
	at org.example.JavadocMetadataScraperTest.testEmptyPropretiesList(JavadocMetadataScraperTest.java:37)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   JavadocMetadataScraperTest.testCheckModuleAndEnumTokenValues:20->checkModuleMeta:91 Fully qualified name doesn't match: RightCurly ==> expected: <inputs.right-curly-check.RightCurlyCheck> but was: <github.checkstyle.metadata-gen.src.test.resources.java.inputs.right-curly-check.RightCurlyCheck>
[ERROR]   JavadocMetadataScraperTest.testEmptyPropretiesList:37->checkModuleMeta:91 Fully qualified name doesn't match: UpperEll ==> expected: <inputs.upper-ell-check.UpperEllCheck> but was: <github.checkstyle.metadata-gen.src.test.resources.java.inputs.upper-ell-check.UpperEllCheck>
[ERROR]   JavadocMetadataScraperTest.testExampleLessModuleDescription:42->checkModuleMeta:91 Fully qualified name doesn't match: ExampleLessUpperEll ==> expected: <inputs.upper-ell-check.ExampleLessUpperEllCheck> but was: <github.checkstyle.metadata-gen.src.test.resources.java.inputs.upper-ell-check.ExampleLessUpperEllCheck>
[ERROR]   JavadocMetadataScraperTest.testFileFilterModuleAndEmptyViolationMessageKeys:25->checkModuleMeta:91 Fully qualified name doesn't match: BeforeExecutionExclusionFileFilter ==> expected: <inputs.before-execution-exclusion-file-filter.BeforeExecutionExclusionFileFilter> but was: <github.checkstyle.metadata-gen.src.test.resources.java.inputs.before-execution-exclusion-file-filter.BeforeExecutionExclusionFileFilter>
[ERROR]   JavadocMetadataScraperTest.testFilterModule:31->checkModuleMeta:91 Fully qualified name doesn't match: SuppressionXpathSingleFilter ==> expected: <inputs.suppression-xpath-single-filter.SuppressionXpathSingleFilter> but was: <github.checkstyle.metadata-gen.src.test.resources.java.inputs.suppression-xpath-single-filter.SuppressionXpathSingleFilter>
[INFO] 
[ERROR] Tests run: 6, Failures: 5, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.874 s
[INFO] Finished at: 2020-08-13T06:36:38-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project metadata-gen: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/rivanov/java/github/checkstyle/metadata-gen/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by romani** [comment]
diff on file system after build:
```
✔ ~/java/github/checkstyle/metadata-gen [master|✚ 6] 
$ git diff
diff --git a/src/test/resources/java/inputs/before-execution-exclusion-file-filter/checkstylemeta-BeforeExecutionExclusionFileFilter.xml b/src/test/resources/java/inputs/before-execution-exclusion-file-filter/checkstylemeta-BeforeExecutionExclusionFileFilter.xml
index 3879673..497cedb 100644
--- a/src/test/resources/java/inputs/before-execution-exclusion-file-filter/checkstylemeta-BeforeExecutionExclusionFileFilter.xml
+++ b/src/test/resources/java/inputs/before-execution-exclusion-file-filter/checkstylemeta-BeforeExecutionExclusionFileFilter.xml
@@ -2,7 +2,7 @@
 
 <checkstyle-metadata>
   <module>
-    <file-filter name="BeforeExecutionExclusionFileFilter" fully-qualified-name="inputs.before-execution-exclusion-file-filter.BeforeExecutionExclusionFileFilter" parent="com.puppycrawl.tools.checkstyle.Checker">
+    <file-filter name="BeforeExecutionExclusionFileFilter" fully-qualified-name="github.checkstyle.metadata-gen.src.test.resources.java.inputs.before-execution-exclusion-file-filter.BeforeExecutionExclusionFileFilter" parent="com.puppycrawl.tools.checkstyle.Checker">
       <description><![CDATA[<p>
  File filter {@code BeforeExecutionExclusionFileFilter} decides which files should be
  excluded from being processed by the utility.
diff --git a/src/test/resources/java/inputs/right-curly-check/checkstylemeta-RightCurlyCheck.xml b/src/test/resources/java/inputs/right-curly-check/checkstylemeta-RightCurlyCheck.xml
index 1e37bec..2aa85d5 100644
--- a/src/test/resources/java/inputs/right-curly-check/checkstylemeta-RightCurlyCheck.xml
+++ b/src/test/resources/java/inputs/right-curly-check/checkstylemeta-RightCurlyCheck.xml
@@ -2,7 +2,7 @@
 
 <checkstyle-metadata>
   <module>
-    <check name="RightCurly" fully-qualified-name="inputs.right-curly-check.RightCurlyCheck" parent="com.puppycrawl.tools.checkstyle.TreeWalker">
+    <check name="RightCurly" fully-qualified-name="github.checkstyle.metadata-gen.src.test.resources.java.inputs.right-curly-check.RightCurlyCheck" parent="com.puppycrawl.tools.checkstyle.TreeWalker">
       <description><![CDATA[<p>
  Checks the placement of right curly braces ({@code '}'}) for code blocks. This check supports
  if-else, try-catch-finally blocks, while-loops, for-loops,
diff --git a/src/test/resources/java/inputs/suppression-xpath-single-filter/checkstylemeta-SuppressionXpathSingleFilter.xml b/src/test/resources/java/inputs/suppression-xpath-single-filter/checkstylemeta-SuppressionXpathSingleFilter.xml
index d499386..9c1ce60 100644
--- a/src/test/resources/java/inputs/suppression-xpath-single-filter/checkstylemeta-SuppressionXpathSingleFilter.xml
+++ b/src/test/resources/java/inputs/suppression-xpath-single-filter/checkstylemeta-SuppressionXpathSingleFilter.xml
@@ -2,7 +2,7 @@
 
 <checkstyle-metadata>
   <module>
-    <filter name="SuppressionXpathSingleFilter" fully-qualified-name="inputs.suppression-xpath-single-filter.SuppressionXpathSingleFilter" parent="com.puppycrawl.tools.checkstyle.TreeWalker">
+    <filter name="SuppressionXpathSingleFilter" fully-qualified-name="github.checkstyle.metadata-gen.src.test.resources.java.inputs.suppression-xpath-single-filter.SuppressionXpathSingleFilter" parent="com.puppycrawl.tools.checkstyle.TreeWalker">
       <description><![CDATA[<p>
  Filter {@code SuppressionXpathSingleFilter} suppresses audit events for Checks
  violations in the specified file, class, checks, message, module id, and xpath.
diff --git a/src/test/resources/java/inputs/translation-check/checkstylemeta-PropertyLessTranslationCheck.xml b/src/test/resources/java/inputs/translation-check/checkstylemeta-PropertyLessTranslationCheck.xml
index 71a314a..9834938 100644
--- a/src/test/resources/java/inputs/translation-check/checkstylemeta-PropertyLessTranslationCheck.xml
+++ b/src/test/resources/java/inputs/translation-check/checkstylemeta-PropertyLessTranslationCheck.xml
@@ -2,7 +2,7 @@
 
 <checkstyle-metadata>
   <module>
-    <check name="PropertyLessTranslation" fully-qualified-name="inputs.translation-check.PropertyLessTranslationCheck" parent="com.puppycrawl.tools.checkstyle.Checker">
+    <check name="PropertyLessTranslation" fully-qualified-name="github.checkstyle.metadata-gen.src.test.resources.java.inputs.translation-check.PropertyLessTranslationCheck" parent="com.puppycrawl.tools.checkstyle.Checker">
       <description><![CDATA[<p>
  Ensures the correct translation of code by checking property files for consistency
  regarding their keys. Two property files describing one and the same context
diff --git a/src/test/resources/java/inputs/upper-ell-check/checkstylemeta-ExampleLessUpperEllCheck.xml b/src/test/resources/java/inputs/upper-ell-check/checkstylemeta-ExampleLessUpperEllCheck.xml
index 2fb6c2e..54e29ef 100644
--- a/src/test/resources/java/inputs/upper-ell-check/checkstylemeta-ExampleLessUpperEllCheck.xml
+++ b/src/test/resources/java/inputs/upper-ell-check/checkstylemeta-ExampleLessUpperEllCheck.xml
@@ -2,7 +2,7 @@
 
 <checkstyle-metadata>
   <module>
-    <check name="ExampleLessUpperEll" fully-qualified-name="inputs.upper-ell-check.ExampleLessUpperEllCheck" parent="com.puppycrawl.tools.checkstyle.TreeWalker">
+    <check name="ExampleLessUpperEll" fully-qualified-name="github.checkstyle.metadata-gen.src.test.resources.java.inputs.upper-ell-check.ExampleLessUpperEllCheck" parent="com.puppycrawl.tools.checkstyle.TreeWalker">
       <description><![CDATA[<p>
  Checks that long constants are defined with an upper ell. That is {@code 'L'}
  and not {@code 'l'}. This is in accordance with the Java Language Specification,
diff --git a/src/test/resources/java/inputs/upper-ell-check/checkstylemeta-UpperEllCheck.xml b/src/test/resources/java/inputs/upper-ell-check/checkstylemeta-UpperEllCheck.xml
index 05a0565..72102c3 100644
--- a/src/test/resources/java/inputs/upper-ell-check/checkstylemeta-UpperEllCheck.xml
+++ b/src/test/resources/java/inputs/upper-ell-check/checkstylemeta-UpperEllCheck.xml
@@ -2,7 +2,7 @@
 
 <checkstyle-metadata>
   <module>
-    <check name="UpperEll" fully-qualified-name="inputs.upper-ell-check.UpperEllCheck" parent="com.puppycrawl.tools.checkstyle.TreeWalker">
+    <check name="UpperEll" fully-qualified-name="github.checkstyle.metadata-gen.src.test.resources.java.inputs.upper-ell-check.UpperEllCheck" parent="com.puppycrawl.tools.checkstyle.TreeWalker">
       <description><![CDATA[<p>
  Checks that long constants are defined with an upper ell. That is {@code 'L'}
  and not {@code 'l'}. This is in accordance with the Java Language Specification,

```

**Comment by romani** [comment]
fix is merged.
